services:
  ivms-4200:
    build: .
    container_name: ivms-4200
    ports:
      - "3389:3389"
      - "6080:6080"
    environment:
      - AUTO_INSTALL_IVMS=0
    volumes:
      - ./installer:/opt/ivms/installer
      - ivms_wine32:/home/ivms/.wine32
      - ivms_logs:/opt/ivms/logs
    restart: unless-stopped

volumes:
  ivms_wine32:
  ivms_logs:
